<?php include('header/header.php');?>
<div class="container-fluid">
<div id="filter-overlay"></div>
<div class="category-list-section">
<div class="row">
<div class="product loading-icon v2 hide"></div>
<div class="col-md-2 col-sm-3 hidden-xs sku-filter">
<div class="sku-filter-container">
<div class="filter-content-wrap">
<span class="filter-by">Filter By</span>
<input type="hidden" value="brand" class="filter-type">
<div id="brand-box" class="row filter-facet">
<div class="col-md-12 filter-heading">BRAND</div>
<div class="col-md-12">
<input type="text" placeholder="Search Brand" class="brand-search">
<div class="filter-items scroll">
<label class="filter-item">
	<input type="checkbox" name="brand" value="healthvit" data-id="healthvit" class="filter-inputbox">
	<span class="filter-name">HEALTHVIT</span>
	<span class="filter-count">59</span>
</label>

<label class="filter-item">
	<input type="checkbox" name="brand" value="sri sri ayurveda" data-id="sri-sri-ayurveda" class="filter-inputbox">
	<span class="filter-name">SRI SRI AYURVEDA</span>
	<span class="filter-count">35</span>
</label>
<label class="filter-item">
	<input type="checkbox" name="brand" value="healthaid" data-id="healthaid" class="filter-inputbox"><span class="filter-name">HEALTHAID</span><span class="filter-count">28</span>
</label>
<label class="filter-item">
	<input type="checkbox" name="brand" value="sbl" data-id="sbl" class="filter-inputbox"><span class="filter-name">SBL</span><span class="filter-count">26</span>
</label>
<label class="filter-item">
<input type="checkbox" name="brand" value="jiva" data-id="jiva" class="filter-inputbox"><span class="filter-name">JIVA</span><span class="filter-count">23</span>
</label>
<label class="filter-item"><input type="checkbox" name="brand" value="inlife" data-id="inlife" class="filter-inputbox"><span class="filter-name">INLIFE</span><span class="filter-count">18</span>
</label>
<label class="filter-item"><input type="checkbox" name="brand" value="st.botanica" data-id="st.botanica" class="filter-inputbox"><span class="filter-name">ST.BOTANICA</span><span class="filter-count">18</span></label>
<label class="filter-item"><input type="checkbox" name="brand" value="forever" data-id="forever" class="filter-inputbox"><span class="filter-name">FOREVER</span><span class="filter-count">15</span>
</label>
<label class="filter-item"><input type="checkbox" name="brand" value="allen" data-id="allen" class="filter-inputbox"><span class="filter-name">ALLEN</span><span class="filter-count">14</span>
</label>
<label class="filter-item">
<input type="checkbox" name="brand" value="himalaya" data-id="himalaya" class="filter-inputbox"><span class="filter-name">HIMALAYA</span><span class="filter-count">14</span>
</label>

<label class="filter-item"><input type="checkbox" name="brand" value="patanjali" data-id="patanjali" class="filter-inputbox"><span class="filter-name">PATANJALI</span><span class="filter-count">12</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="sebamed" data-id="sebamed" class="filter-inputbox"><span class="filter-name">SEBAMED</span><span class="filter-count">11</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="zenith nutrition" data-id="zenith-nutrition" class="filter-inputbox"><span class="filter-name">ZENITH NUTRITION</span><span class="filter-count">9</span></label><label class="filter-item"><input type="checkbox" name="brand" value="baksons" data-id="baksons" class="filter-inputbox"><span class="filter-name">BAKSONS</span><span class="filter-count">8</span></label><label class="filter-item"><input type="checkbox" name="brand" value="hamdard" data-id="hamdard" class="filter-inputbox"><span class="filter-name">HAMDARD</span><span class="filter-count">8</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="imc" data-id="imc" class="filter-inputbox"><span class="filter-name">IMC</span><span class="filter-count">8</span></label><label class="filter-item"><input type="checkbox" name="brand" value="morpheme" data-id="morpheme" class="filter-inputbox"><span class="filter-name">MORPHEME</span><span class="filter-count">8</span></label><label class="filter-item"><input type="checkbox" name="brand" value="dermadew" data-id="dermadew" class="filter-inputbox"><span class="filter-name">DERMADEW</span><span class="filter-count">5</span></label><label class="filter-item"><input type="checkbox" name="brand" value="kudos" data-id="kudos" class="filter-inputbox"><span class="filter-name">KUDOS</span><span class="filter-count">5</span></label><label class="filter-item"><input type="checkbox" name="brand" value="amway" data-id="amway" class="filter-inputbox"><span class="filter-name">AMWAY</span><span class="filter-count">4</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="cetaphil" data-id="cetaphil" class="filter-inputbox"><span class="filter-name">CETAPHIL</span><span class="filter-count">4</span></label><label class="filter-item"><input type="checkbox" name="brand" value="depiwhite" data-id="depiwhite" class="filter-inputbox"><span class="filter-name">DEPIWHITE</span><span class="filter-count">4</span></label><label class="filter-item"><input type="checkbox" name="brand" value="elovera" data-id="elovera" class="filter-inputbox"><span class="filter-name">ELOVERA</span><span class="filter-count">4</span></label><label class="filter-item"><input type="checkbox" name="brand" value="first step" data-id="first-step" class="filter-inputbox"><span class="filter-name">FIRST STEP</span><span class="filter-count">4</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="indian remedies" data-id="indian-remedies" class="filter-inputbox"><span class="filter-name">INDIAN REMEDIES</span><span class="filter-count">4</span></label><label class="filter-item"><input type="checkbox" name="brand" value="moisturex" data-id="moisturex" class="filter-inputbox"><span class="filter-name">MOISTUREX</span><span class="filter-count">4</span></label><label class="filter-item"><input type="checkbox" name="brand" value="planet ayurveda" data-id="planet-ayurveda" class="filter-inputbox"><span class="filter-name">PLANET AYURVEDA</span><span class="filter-count">4</span></label><label class="filter-item"><input type="checkbox" name="brand" value="venusia" data-id="venusia" class="filter-inputbox"><span class="filter-name">VENUSIA</span><span class="filter-count">4</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="ahaglow" data-id="ahaglow" class="filter-inputbox"><span class="filter-name">AHAGLOW</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="avarta" data-id="avarta" class="filter-inputbox"><span class="filter-name">AVARTA</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="ayur" data-id="ayur" class="filter-inputbox"><span class="filter-name">AYUR</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="dewsoft" data-id="dewsoft" class="filter-inputbox"><span class="filter-name">DEWSOFT</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="khadi" data-id="khadi" class="filter-inputbox"><span class="filter-name">KHADI</span><span class="filter-count">3</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="organic india" data-id="organic-india" class="filter-inputbox"><span class="filter-name">ORGANIC INDIA</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="sunban" data-id="sunban" class="filter-inputbox"><span class="filter-name">SUNBAN</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="wow" data-id="wow" class="filter-inputbox"><span class="filter-name">WOW</span><span class="filter-count">3</span></label><label class="filter-item"><input type="checkbox" name="brand" value="add veda" data-id="add-veda" class="filter-inputbox"><span class="filter-name">ADD VEDA</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="aimil" data-id="aimil" class="filter-inputbox"><span class="filter-name">AIMIL</span><span class="filter-count">2</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="ansolar" data-id="ansolar" class="filter-inputbox"><span class="filter-name">ANSOLAR</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="aveeno" data-id="aveeno" class="filter-inputbox"><span class="filter-name">AVEENO</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="avene(roche)" data-id="avene-roche" class="filter-inputbox"><span class="filter-name">AVENE(ROCHE)</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="biohome" data-id="biohome" class="filter-inputbox"><span class="filter-name">BIOHOME</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="biotino" data-id="biotino" class="filter-inputbox"><span class="filter-name">BIOTINO</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="fash" data-id="fash" class="filter-inputbox"><span class="filter-name">FASH</span><span class="filter-count">2</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="figaro" data-id="figaro" class="filter-inputbox"><span class="filter-name">FIGARO</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="golite" data-id="golite" class="filter-inputbox"><span class="filter-name">GOLITE</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="kojivit" data-id="kojivit" class="filter-inputbox"><span class="filter-name">KOJIVIT</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="mederma" data-id="mederma" class="filter-inputbox"><span class="filter-name">MEDERMA</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="melaglow" data-id="melaglow" class="filter-inputbox"><span class="filter-name">MELAGLOW</span><span class="filter-count">2</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="moiz" data-id="moiz" class="filter-inputbox"><span class="filter-name">MOIZ</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="niltan" data-id="niltan" class="filter-inputbox"><span class="filter-name">NILTAN</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="parasoft" data-id="parasoft" class="filter-inputbox"><span class="filter-name">PARASOFT</span><span class="filter-count">2</span></label>
<label class="filter-item"><input type="checkbox" name="brand" value="physiogel" data-id="physiogel" class="filter-inputbox"><span class="filter-name">PHYSIOGEL</span><span class="filter-count">2</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="rivela" data-id="rivela" class="filter-inputbox"><span class="filter-name">RIVELA</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="suncros" data-id="suncros" class="filter-inputbox"><span class="filter-name">SUNCROS</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="tvaksh" data-id="tvaksh" class="filter-inputbox"><span class="filter-name">TVAKSH</span><span class="filter-count">2</span></label><label class="filter-item"><input type="checkbox" name="brand" value="a-derma" data-id="a-derma" class="filter-inputbox"><span class="filter-name">A-DERMA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="acnemoist" data-id="acnemoist" class="filter-inputbox"><span class="filter-name">ACNEMOIST</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="adven" data-id="adven" class="filter-inputbox"><span class="filter-name">ADVEN</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="allexo" data-id="allexo" class="filter-inputbox"><span class="filter-name">ALLEXO</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="alograce" data-id="alograce" class="filter-inputbox"><span class="filter-name">ALOGRACE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="atogla" data-id="atogla" class="filter-inputbox"><span class="filter-name">ATOGLA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="baidyanath" data-id="baidyanath" class="filter-inputbox"><span class="filter-name">BAIDYANATH</span>

<span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="ban a tan" data-id="ban-a-tan" class="filter-inputbox"><span class="filter-name">BAN A TAN</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="beautypill" data-id="beautypill" class="filter-inputbox"><span class="filter-name">BEAUTYPILL</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="bio" data-id="bio" class="filter-inputbox"><span class="filter-name">BIO</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="biocutis" data-id="biocutis" class="filter-inputbox"><span class="filter-name">BIOCUTIS</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="bioforce" data-id="bioforce" class="filter-inputbox"><span class="filter-name">BIOFORCE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="bioma" data-id="bioma" class="filter-inputbox"><span class="filter-name">BIOMA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="boroline" data-id="boroline" class="filter-inputbox"><span class="filter-name">BOROLINE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="brevoxyl" data-id="brevoxyl" class="filter-inputbox"><span class="filter-name">BREVOXYL</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="chaptex" data-id="chaptex" class="filter-inputbox"><span class="filter-name">CHAPTEX</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="charak" data-id="charak" class="filter-inputbox"><span class="filter-name">CHARAK</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="cutiwash soft" data-id="cutiwash-soft" class="filter-inputbox"><span class="filter-name">CUTIWASH SOFT</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="cutiyt total" data-id="cutiyt-total" class="filter-inputbox"><span class="filter-name">CUTIYT TOTAL</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="daffy" data-id="daffy" class="filter-inputbox"><span class="filter-name">DAFFY</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="dcr" data-id="dcr" class="filter-inputbox"><span class="filter-name">DCR</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="decora-forte" data-id="decora-forte" class="filter-inputbox"><span class="filter-name">DECORA-FORTE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="derclean" data-id="derclean" class="filter-inputbox"><span class="filter-name">DERCLEAN</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="dr willmar schwabe" data-id="dr-willmar-schwabe" class="filter-inputbox"><span class="filter-name">DR WILLMAR SCHWABE</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="e-vit" data-id="e-vit" class="filter-inputbox"><span class="filter-name">E-VIT</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="emolene" data-id="emolene" class="filter-inputbox"><span class="filter-name">EMOLENE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="episoft" data-id="episoft" class="filter-inputbox"><span class="filter-name">EPISOFT</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="ever c 20" data-id="ever-c-20" class="filter-inputbox"><span class="filter-name">EVER C 20</span><span class="filter-count">1</span></label>
<label class="filter-item"><input type="checkbox" name="brand" value="evion" data-id="evion" class="filter-inputbox"><span class="filter-name">EVION</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="eyez" data-id="eyez" class="filter-inputbox"><span class="filter-name">EYEZ</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="fairlite" data-id="fairlite" class="filter-inputbox"><span class="filter-name">FAIRLITE</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="glyco-a" data-id="glyco-a" class="filter-inputbox"><span class="filter-name">GLYCO-A</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="happyglow" data-id="happyglow" class="filter-inputbox"><span class="filter-name">HAPPYGLOW</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="kelo-cote" data-id="kelo-cote" class="filter-inputbox"><span class="filter-name">KELO-COTE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="klmklin aha" data-id="klmklin-aha" class="filter-inputbox"><span class="filter-name">KLMKLIN AHA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="kojic" data-id="kojic" class="filter-inputbox"><span class="filter-name">KOJIC</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="krack" data-id="krack" class="filter-inputbox"><span class="filter-name">KRACK</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="kz" data-id="kz" class="filter-inputbox"><span class="filter-name">KZ</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="la shield" data-id="la-shield" class="filter-inputbox"><span class="filter-name">LA SHIELD</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="lacto calamine" data-id="lacto-calamine" class="filter-inputbox"><span class="filter-name">LACTO CALAMINE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="ls dew" data-id="ls-dew" class="filter-inputbox"><span class="filter-name">LS DEW</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="medisynth" data-id="medisynth" class="filter-inputbox"><span class="filter-name">MEDISYNTH</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="melagard" data-id="melagard" class="filter-inputbox"><span class="filter-name">MELAGARD</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="melano-tx" data-id="melano-tx" class="filter-inputbox"><span class="filter-name">MELANO-TX</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="melawash" data-id="melawash" class="filter-inputbox"><span class="filter-name">MELAWASH</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="nipcare" data-id="nipcare" class="filter-inputbox"><span class="filter-name">NIPCARE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="nmf e" data-id="nmf-e" class="filter-inputbox"><span class="filter-name">NMF E</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="nycil" data-id="nycil" class="filter-inputbox"><span class="filter-name">NYCIL</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="oilatum" data-id="oilatum" class="filter-inputbox"><span class="filter-name">OILATUM</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="olemessa" data-id="olemessa" class="filter-inputbox"><span class="filter-name">OLEMESSA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="papulex" data-id="papulex" class="filter-inputbox"><span class="filter-name">PAPULEX</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="photobloc" data-id="photobloc" class="filter-inputbox"><span class="filter-name">PHOTOBLOC</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="radant" data-id="radant" class="filter-inputbox"><span class="filter-name">RADANT</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="rebask" data-id="rebask" class="filter-inputbox"><span class="filter-name">REBASK</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="rejuglow" data-
id="rejuglow" class="filter-inputbox"><span class="filter-name">REJUGLOW</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="roop mantra ayurvedic cream" data-id="roop-mantra-ayurvedic-cream" class="filter-inputbox"><span class="filter-name">ROOP MANTRA AYURVEDIC CREAM</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="salactin" data-id="salactin" class="filter-inputbox"><span class="filter-name">SALACTIN</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="shadowz" data-id="shadowz" class="filter-inputbox"><span class="filter-name">SHADOWZ</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="sirona" data-id="sirona" class="filter-inputbox"><span class="filter-name">SIRONA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="stretch nil" data-id="stretch-nil" class="filter-inputbox"><span class="filter-name">STRETCH NIL</span><span class="filter-count">1</span></label>

<label class="filter-item"><input type="checkbox" name="brand" value="sunclip" data-id="sunclip" class="filter-inputbox"><span class="filter-name">SUNCLIP</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="sungrace" data-id="sungrace" class="filter-inputbox"><span class="filter-name">SUNGRACE</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="sunprotek" data-id="sunprotek" class="filter-inputbox"><span class="filter-name">SUNPROTEK</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="suthol" data-id="suthol" class="filter-inputbox"><span class="filter-name">SUTHOL</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="vicco" data-id="vicco" class="filter-inputbox"><span class="filter-name">VICCO</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="wunder" data-id="wunder" class="filter-inputbox"><span class="filter-name">WUNDER</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="xerina" data-id="xerina" class="filter-inputbox"><span class="filter-name">XERINA</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="zitmoist" data-id="zitmoist" class="filter-inputbox"><span class="filter-name">ZITMOIST</span><span class="filter-count">1</span></label><label class="filter-item"><input type="checkbox" name="brand" value="zyndet" data-id="zyndet" class="filter-inputbox"><span class="filter-name">ZYNDET</span><span class="filter-count">1</span></label>
</div></div></div>

<input type="hidden" value="discount" class="filter-type"><div id="discount-box" class="row filter-facet"><div class="col-md-12 filter-heading">DISCOUNT</div><div class="col-md-12"><div class="filter-items"><label class="filter-item"><input type="checkbox" name="discount" value="0" data-id="0.0" class="filter-inputbox"><span class="filter-name">Less than 10%</span><span class="filter-count">47</span></label><label class="filter-item"><input type="checkbox" name="discount" value="10" data-id="10.0" class="filter-inputbox"><span class="filter-name">10% and above</span><span class="filter-count">240</span></label><label class="filter-item"><input type="checkbox" name="discount" value="20" data-id="20.0" class="filter-inputbox"><span class="filter-name">20% and above</span><span class="filter-count">188</span></label><label class="filter-item"><input type="checkbox" name="discount" value="30" data-id="30.0" class="filter-inputbox"><span class="filter-name">30% and above</span><span class="filter-count">66</span></label></div></div></div></div></div></div>

<!--start product-->
<div class="col-md-10 col-sm-9 sku-list"><div class="cat-breadcrumb">
<a href="<?php print base_url('Welcome');?>" class="home-link button-text">Home</a><i class="fa fa-angle-right breadcrumb-icon"></i><span>Personal Care</span><i class="fa fa-angle-right breadcrumb-icon"></i><span>Skin Care</span>
	</div><h1 class="display-inline-inline sku-page-cat">Skin Care</h1><div class="row"><div class="col-sm-8"><a style="color: #212121;" href="offers.html" class="button-text category-description">Up to 30% Off on Skin Care products + Extra 10% Off using coupon: HEALTH10</a></div>

	<div class="col-sm-4 text-right">
	<label class="sort-label">Sort By</label><div class="sort dropdown"><a class="button-text sort-button"><span data-key="relevance">Relevance</span><i class="fa fa-caret-down sort-icon"></i></a><ul class="dropdown-menu sort-dropdown"><li data-key="relevance" data-type="sort" class="sort-name text-left">Relevance</li><li data-key="price_low" data-type="sort" class="sort-name text-left">Price: Low to High</li><li data-key="price_high" data-type="sort" class="sort-name text-left">Price: High to Low</li><li data-key="discount" data-type="sort" class="sort-name text-left">Discount</li></ul></div></div>	
	</div>
	<div class="filter-list hidden-xs"><a class="clear-filter button-text hide">CLEAR FILTERS</a>
	</div>
	<div class="row mt0 js-alert-section">
<!--single product-->
	<div class="col-md-3 col-sm-4 col-xs-12 dia-sku">
	<div class="sku-container">
	<div class="content-wrap">
	<a href="<?php print base_url('product_description');?>">
	<div class="sku-img">
	<img src="<?php print base_url('');?>assets/res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1483342649/h1c9q4lpvqmf7zdm2dhh.jpg" onerror="this.src = '<?php print base_url('');?>assets/img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="WOW ULTIMATE UNDER EYE &amp; FACIAL GEL">
	</div>
	<div class="sku-name">WOW ULTIMATE UNDER EYE &amp; FACIAL GEL</div></a><div class="sku-pack">bottle of 50 ML gel</div><div class="sku-price"><div class="sku-offer display-inline">Rs 699.00</div><div class="sku-actual display-inline">Rs 1999.00</div>
	</div>
	</div>
	<a data-id="340509" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a>
	</div>
	</div>
<!--end single product-->

	<div class="col-md-3 col-sm-4 col-xs-12 dia-sku">
	<div class="sku-container">
	<div class="content-wrap">
	<a href="#">
	<div class="sku-img">
	<img src="<?php print base_url('');?>assets/res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1460470993/fowbkq6ntajb63z4hjtu.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="HAMDARD ROGHAN BADAM SHIRIN OIL">
	</div>

	<div class="sku-name">HAMDARD ROGHAN BADAM SHIRIN OIL</div></a>
	<div class="sku-pack">bottle of 100 ML oil</div>
	<div class="sku-price">
	<div class="sku-offer display-inline">Rs 319.00</div>
	<div class="sku-actual display-inline">Rs 385.00</div>
	</div>
	</div>
	<a data-id="328134" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp">
	<div class="add-to-cart-text">Add to cart</div>
	<div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i>
	</div>
	</a>
	</div>
	</div>

	<div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/inlife-papaya-fairness-cream-otc344382.html"><div class="sku-img"><img src="<?php print base_url('');?>assets/res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1490790558/hntqxxqy76jp38plnjn4.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="INLIFE PAPAYA FAIRNESS CREAM"></div><div class="sku-name">INLIFE PAPAYA FAIRNESS CREAM</div></a><div class="sku-pack">jar of 100 GM cream</div><div class="sku-price"><div class="sku-offer display-inline">Rs 153.00</div><div class="sku-actual display-inline">Rs 199.00</div></div></div><a data-id="344382" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div>
	<div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/amway-nutrilite-biotin-cherry-plus-tablet-otc342260.html"><div class="sku-img"><img src="<?php print base_url('');?>assets/res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1487058693/g1n58xokw08z3ucebhuw.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="AMWAY NUTRILITE BIOTIN CHERRY PLUS  TABLET"></div>
	<div class="sku-name">AMWAY NUTRILITE BIOTIN CHERRY PLUS  TABLET</div>
	</a>
		<div class="sku-pack">bottle of 60 tablets</div>
		<div class="sku-price"><div class="sku-offer display-inline">Rs 480.00</div><div class="sku-actual display-inline">Rs 627.00</div></div></div><a data-id="342260" data-avail="yes" data-su="60" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/wow-acne-deep-impact-kit-otc340495.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1483344656/nt5rbftuclpqhiplxfjs.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="WOW ACNE DEEP IMPACT KIT"></div><div class="sku-name">WOW ACNE DEEP IMPACT KIT</div></a><div class="sku-pack">packet of 1 kit</div><div class="sku-price"><div class="sku-offer display-inline">Rs 1499.00</div><div class="sku-actual display-inline">Rs 1999.00</div></div></div><a data-id="340495" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="../../otc/jiva-kumkumadi-oil-otc329868.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1470725043/vrazq4x2pjptri7gjoct.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="JIVA KUMKUMADI  OIL"></div>

		<div class="sku-name">JIVA KUMKUMADI  OIL</div></a><div class="sku-pack">bottle of 20 ML oil</div><div class="sku-price"><div class="sku-offer display-inline">Rs 277.00</div><div class="sku-actual display-inline">Rs 362.00</div></div></div><a data-id="329868" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap">
		<a href="otc/morpheme-castor-pure-coldpressed-oil-pack-of-2-otc341987.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1485947425/gl3wwetqqlmgsqztjh3f.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="MORPHEME  CASTOR PURE COLDPRESSED  OIL (PACK OF 2)"></div>

		<div class="sku-name">MORPHEME  CASTOR PURE COLDPRESSED  OIL (PACK OF 2)</div></a><div class="sku-pack">bottle of 100 ML oil</div><div class="sku-price"><div class="sku-offer display-inline">Rs 299.00</div><div class="sku-actual display-inline">Rs 350.00</div></div></div><a data-id="341987" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div>

		<div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/lukoskin-liquid-otc119757.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1491217518/mqdwkyqbjpu0sgjxkr2u.png" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="LUKOSKIN LIQUID"></div>

		<div class="sku-name">LUKOSKIN LIQUID</div></a><div class="sku-pack">bottle of 100 ML liquid</div><div class="sku-price"><div class="sku-offer display-inline">Rs 389.00</div><div class="sku-actual display-inline">Rs 458.00</div></div></div><a data-id="119757" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/forever-aloe-vera-gel-otc330106.html">
		<div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1470220466/grputrqbzrcyiv2g5th7.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="FOREVER ALOE VERA GEL"></div>

		<div class="sku-name">FOREVER ALOE VERA GEL</div></a><div class="sku-pack">bottle of 1 LTR gel</div><div class="sku-price"><div class="sku-offer display-inline">Rs 878.00</div><div class="sku-actual display-inline">Rs 1394.00</div></div></div><a data-id="330106" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/himalaya-clarina-anti-acne-kit-otc131452.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1453447792/yjaau8uqtccwam8etwd6.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="HIMALAYA CLARINA ANTI-ACNE KIT"></div>

		<div class="sku-name">HIMALAYA CLARINA ANTI-ACNE KIT</div></a><div class="sku-pack">packet of 1 kit</div><div class="sku-price"><div class="sku-offer display-inline">Rs 215.00</div><div class="sku-actual display-inline">Rs 260.00</div></div></div><a data-id="131452" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp">
		<div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div>

		<div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/healthvit-aroma-evening-prim-rose-essential-oil-otc340625.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1483700372/jzkyssdsotbwavzeb4i1.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="HEALTHVIT AROMA EVENING PRIM ROSE  ESSENTIAL OIL"></div>
		<div class="sku-name">HEALTHVIT AROMA EVENING PRIM ROSE  ESSENTIAL OIL</div></a><div class="sku-pack">bottle of 30 ML oil</div><div class="sku-price"><div class="sku-offer display-inline">Rs 263.00</div><div class="sku-actual display-inline">Rs 400.00</div></div></div><a data-id="340625" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div>

		<div class="col-md-3 col-sm-4 col-xs-12 dia-sku"><div class="sku-container"><div class="content-wrap"><a href="otc/inlife-aloe-vera-face-gel-otc344385.html"><div class="sku-img"><img src="res.cloudinary.com/du8msdgbj/image/upload/w_380%2ch_380%2cc_fit%2ca_ignore%2cq_60/v1490790595/ditzrrqfye1dtczjmyaa.jpg" onerror="this.src = 'img.1mg.com/images/otc_image_na.png'; this.alt = 'Health Product Image Default';" alt="INLIFE ALOE VERA FACE GEL"></div><div class="sku-name">INLIFE ALOE VERA FACE GEL</div></a><div class="sku-pack">jar of 100 GM gel</div><div class="sku-price"><div class="sku-offer display-inline">Rs 139.00</div><div class="sku-actual display-inline">Rs 180.00</div></div></div><a data-id="344385" data-avail="yes" data-su="1" class="value submit-btn js-avail button-text btn btn-checkout btn-add-sku-to-cart category-sku-add-to-cart btn btn-primary crtDiaOp"><div class="add-to-cart-text">Add to cart</div><div class="add-to-cart-arrow"><i class="fa fa-long-arrow-right fa-2x"></i></div></a></div></div><input type="hidden" value="true" class="hasMoreFlag"></div>
		
		<div class="row text-center"><div class="col-md-12"><a data-number="1" data-size="12" data-url="/api/v3/getMoreOTC/19?" href="skin-care-19b4df.html?pageNumber=1&amp;pageSize=12" class="pgntnCntnrBar btn btn-primary text-small button-text">Load More</a><div class="loading-icon v2 hide"></div></div>
		</div>
		</div>

		</div></div></div></div></div>


		<?php include('header/footer.php');?>